### ISSUE TITLE
creating tickets doesn't do the right thing

### ISSUE THREAD

**Issue by rizen** [plainblack/TGCv#10]
It should add the ticket to the list above, and redirect you to the ticket's page. It does neither. 

Maybe it's supposed to, but it gets an object assign error

**Comment by perlDreamer** [comment]
I tried this on my laptop, and it works fine.  I'll make sure that the ving_maintenance branch is merged into main and push it out.

**Comment by rizen** [comment]
I can replicate it on my computer. The exact error message is: Unhandled Promise Rejection: TypeError: Object.assign requires that input parameter not be null or undefined

Perhaps it's a Safari thing. I'll try it in chrome next.

**Comment by rizen** [comment]
You are operating out of main, not your branch right?

**Comment by rizen** [comment]
Fails on Chrome as well:

Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at assign (<anonymous>)
    at pinia.js?v=6b2b947e:1027:7
    at Proxy.$patch (pinia.js?v=6b2b947e:999:7)
    at Proxy.$reset2 (pinia.js?v=6b2b947e:1026:10)
    at Proxy.dispose (useVingRecord.mjs:197:22)
    at Proxy.<anonymous> (pinia.js?v=6b2b947e:1062:22)
    at store.<computed> (pinia.js?v=6b2b947e:743:44)
    at VingKind.dispose (useVingKind.mjs:224:20)
    at HardwareItemTaskSelector.vue:33:19
    at vue-router.mjs?v=6b2b947e:1357:52

**Comment by perlDreamer** [comment]
Operating out of main and using Chrome.

**Comment by rizen** [comment]
fixed

**Comment by perlDreamer** [comment]
The extra fetch of tasks happens when an HardwareItem is chosen for the ticket.  The tasks specific to that Item are fetched.

The dispose dies on the first call to the first task, and it's a valid task, not a duplicate.

The problem is that there are 2 task lists, one partial list inside the composable for selecting Items and Tasks, and another full list for the selector in the search dropdown.  They both try to dispose the same objects, and one fails.

**Comment by rizen** [comment]
fixed by using the new ego behavior
