### ISSUE TITLE
Changes Requested

### ISSUE THREAD

**Issue by vrby** [plainblack/TGCv#34]
1.  Can we put a little more info in the info sent to the Slack channel.  Maybe the equipment name or some abbreviated portion of the description.  It will help the mechanics know when a ding is just an update to an existing ticket, a new thing, etc. 
2. Can we add a "Claimed by" so that anyone looking at the ticket system knows which mechanic is working on an issue (and that the issue is even being looked at).  I'm trying to avoid crafters looking for mechanics so if we can provide a signifier that a mechanic has looked at this ticket that would help. I'd like this field displayed on the main ticket list page as well.  I know it might mean squishing things down. 
3.  Mechanics have expressed an interest in sending ticket notifications to a specific slack channel so it doesn't interrupt what's happening in the main mechanic channel.  I know I'd have to set up the actual channel, I just don't know what it takes on your end to direct stuff there.

**Comment by perlDreamer** [comment]
1. All of the information you're requesting can be added to the Slack ping for ArtieCee.  You want the equipment name and the first 50 characters from the description?
3. If you set up a new channel, I'll just need the new channel ID, and you'll need to invite ArtieCee into the channel (and me too, for debugging/monitoring).

Adding Claimed By is more involved.  There are at leasts a couple of ways to do it.  We could just add the initials of the first person to comment on it (quick and easy, but maybe not accurate all the time), or we could add another field to the ticket so that it works like a Warehouse Project (requires database upgrade).

**Comment by perlDreamer** [comment]
The description field is markdown, so I can't easily give you the first 50 characters.  I have the claimed by field and the equipment name in the Slack channel ready to deploy.
